<a href="https://colab.research.google.com/github/ayeshabaloch123/Data-Science-Analytics/blob/main/20SW044_Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
             ###TASK___1#############
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [ ]:
             ###TASK___2#############
import numpy as np
X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print("Original Array:\n", X)
print("\nOdd Numbers Array:\n", Y)

Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Odd Numbers Array:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [ ]:
             ###TASK___3#############
import numpy as np


X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [ ]:
             ###TASK___4#############
import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-1.42796080e+00 -2.07210792e-01  1.24015759e+00 ... -1.53969796e-01
   2.66977802e-01 -1.24564912e-01]
 [ 1.16170573e+00 -8.25174993e-02  8.27274724e-01 ...  1.03987702e+00
  -7.05038714e-01 -3.67190688e-01]
 [ 1.09991623e+00  1.23703899e+00 -1.38038469e+00 ...  3.92675722e-01
   4.93234811e-01  1.01374852e+00]
 ...
 [-1.63117960e+00 -2.47633343e-01 -6.00260770e-01 ...  8.44839299e-01
  -6.40100902e-01 -8.69922482e-01]
 [ 4.63484401e-01 -2.87370766e-01  1.65936010e+00 ... -1.46524417e+00
  -3.53007416e-01  1.28644032e+00]
 [-6.23387384e-04 -1.16159407e+00  4.60735852e-01 ...  9.27848433e-01
   1.54044248e+00 -1.41041160e+00]]
Average of all values in X_norm: 1.2079226507921702e-17
Average of minimum values in each column of X_norm: -1.729619245813326
Average of maximum values in each column of X_norm: 1.723623751799693
Random permutation of row indices: [507 684 464 288 191 449 501   9 779 714 290 130 674